version: '3.5'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
    container_name: ${POSTGRES_DB_CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ${NETWORK}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagechan-back
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - ${NETWORK}

  minio:
    image: minio/minio
    container_name: ${MINIO_CONTAINER_NAME}
    ports:
      - "9050:9000"  # Mapear el puerto 9050 en el host al puerto 9000 en el contenedor para la API S3
      - "9005:9005"  # Puerto 9005 para la consola MinIO
    volumes:
      - "/mnt/data:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data/${MINIO_BUCKET} --console-address ":9005"
    restart: unless-stopped
    networks:
      - ${NETWORK}

  # imagechan-app:
  #   image: node:18  # Usamos Node.js 18
  #   container_name:  imagechan-app
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - '5018:5018'
  #   # command: sh -c "yarn install && yarn dev"
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=5018
  #   networks:
  #     - windows96
  #   depends_on:
  #     - app

networks:
  windows96:
    driver: bridge
    name: windows96
    #external: true


