import { ObjectType, Field, Int } from '@nestjs/graphql';
import { slug } from 'slug-gen';
import { User } from 'src/auth/entities/user.entity';
import { Channel } from 'src/channels/entities/channel.entity';
import { Post } from 'src/post/entities/post.entity';
import { Thread } from 'src/thread/entities/thread.entity';
import { BeforeInsert, BeforeUpdate, Column, DeleteDateColumn, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from 'typeorm';

@ObjectType()
@Entity()
export class Reply {

  @Field(() => String)
  @PrimaryGeneratedColumn('uuid')
  id: string

  // @Field(() => Number, { nullable: true }) // false
  // @Column({ type: 'int', unique: true }) // false
  // @Generated('increment')
  // numberPost: number

  @Field(() => Int, { description: 'Unique post number generated by sequence' })
  @Column({
      type: 'int',
      unique: true,
      default: () => `nextval('global_number_seq')`
  })
  numberPost: number;

  @ManyToOne(
    () => User,
    ( user ) => user.id,
    {
        eager:true
    }
  )
  @Field(
    () => User, 
    { nullable: true }
  )
  createdBy?: User

  @ManyToOne(
    () => Channel,
    (channel) => channel.id,
    {
      eager: true,
      nullable: true, // Asegura que un Post siempre tiene un Channel asociado
    }
  )
  @Field(() => Channel)
  channel?: Channel;

  @Field(() => String)
  @Column()
  title: string

  @Field()
  @Column()
  content: string

  @Field({ nullable: true })
  @Column({nullable:true})
  image?:string

  @Field(() => Boolean)
  @Column('bool',{
    default: true
  })
  anonPost: boolean

  @Field()
  @Column()
  slug: string

  @ManyToOne(() => Thread, (thread) => thread.reply, {
    eager: true,
    nullable: false,
  })
  @Field(() => Thread)
  thread: Thread

  // @ManyToOne(() => Reply, (reply) => reply.children, { nullable: true })
  // @Field(() => Reply, { nullable: true })
  // parent?: Reply;

  // @OneToMany(() => Reply, (reply) => reply.parent, { nullable: true })
  // @Field(() => [Reply], { nullable: true })
  // children?: Reply[];
  
  @Field({ nullable: true })
  @Column({nullable:true})
  created_at?: Date

  @Field({ nullable: true })
  @Column({nullable:true})
  updated_at?: Date

  @Field({ nullable: true })
  @DeleteDateColumn({nullable:true})
  deleted_at?: Date

  @BeforeInsert()
  slugBeforeInsert(){
    this.slug = slug(this.title)
  }


  @BeforeInsert()
  setCreatedAt() {
    const currentDate = new Date()
    this.created_at = currentDate
  }

  @BeforeUpdate()
  setUpdatedAt() {
    this.updated_at = new Date()
  }




}
